// Turns a --dump-dom of prototype.html#static-<Key> (stdin) into design-reference/screens/<Key>.html.
// Usage: node snapshot.js <Key> < dump.html
const fs = require('fs'), path = require('path');
const key = process.argv[2];
let html = fs.readFileSync(0, 'utf8');
if (!/data-ready="1"/.test(html)) { console.error(`FAIL: snapshot ${key} did not finish rendering`); process.exit(1); }
html = html.replace(/<script[\s\S]*?<\/script>/g, '')
  .replace(/\.\.\/assets\//g, '../../assets/')
  .replace(/^(?!<!doctype)/i, '<!doctype html>\n')
  .replace('<head>', `<head>\n<!-- Generated by .claude/scripts/design.sh from design-reference/prototype.html#static-${key}. Do not edit; change the prototype. -->`);
fs.writeFileSync(path.resolve(__dirname, '../screens', key + '.html'), html);
